[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration"]

[start]
cmd = "frankenphp run --config /assets/Caddyfile"